export const EVENT_ADD_REQUEST = "EVENT_ADD_REQUEST";
export const EVENT_ADD_SUCCESS = "EVENT_ADD_SUCCESS";
export const EVENT_ADD_FAIL = "EVENT_ADD_FAIL";
export const EVENT_ADD_RESET = "EVENT_ADD_RESET";
