export const TASK_ADD_REQUEST = "TASK_ADD_REQUEST";
export const TASK_ADD_SUCCESS = "TASK_ADD_SUCCESS";
export const TASK_ADD_FAIL = "TASK_ADD_FAIL";
export const TASK_ADD_RESET = "TASK_ADD_RESET";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";
export const TASK_DELETE_RESET = "TASK_DELETE_RESET";

export const MY_TASK_REQUEST = "MY_TASK_REQUEST";
export const MY_TASK_SUCCESS = "MY_TASK_SUCCESS";
export const MY_TASK_FAIL = "MY_TASK_FAIL";
export const MY_TASK_RESET = "MY_TASK_RESET";
